// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Header.proto

package org.lwl.netty.message.protobuf;

public final class Header {
  private Header() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageTypeEnum}
   */
  public enum MessageTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>LOGIN_REQ = 1;</code>
     */
    LOGIN_REQ(1),
    /**
     * <code>LOGIN_RESP = 2;</code>
     */
    LOGIN_RESP(2),
    /**
     * <code>LOGOUT = 3;</code>
     */
    LOGOUT(3),
    /**
     * <code>HEARTBEAT_REQ = 4;</code>
     */
    HEARTBEAT_REQ(4),
    /**
     * <code>HEARTBEAT_RESP = 5;</code>
     */
    HEARTBEAT_RESP(5),
    /**
     * <code>PROTOCOL_SUB = 6;</code>
     */
    PROTOCOL_SUB(6),
    /**
     * <code>PROTOCOL_DATA = 7;</code>
     */
    PROTOCOL_DATA(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>LOGIN_REQ = 1;</code>
     */
    public static final int LOGIN_REQ_VALUE = 1;
    /**
     * <code>LOGIN_RESP = 2;</code>
     */
    public static final int LOGIN_RESP_VALUE = 2;
    /**
     * <code>LOGOUT = 3;</code>
     */
    public static final int LOGOUT_VALUE = 3;
    /**
     * <code>HEARTBEAT_REQ = 4;</code>
     */
    public static final int HEARTBEAT_REQ_VALUE = 4;
    /**
     * <code>HEARTBEAT_RESP = 5;</code>
     */
    public static final int HEARTBEAT_RESP_VALUE = 5;
    /**
     * <code>PROTOCOL_SUB = 6;</code>
     */
    public static final int PROTOCOL_SUB_VALUE = 6;
    /**
     * <code>PROTOCOL_DATA = 7;</code>
     */
    public static final int PROTOCOL_DATA_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    public static MessageTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return LOGIN_REQ;
        case 2: return LOGIN_RESP;
        case 3: return LOGOUT;
        case 4: return HEARTBEAT_REQ;
        case 5: return HEARTBEAT_RESP;
        case 6: return PROTOCOL_SUB;
        case 7: return PROTOCOL_DATA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageTypeEnum>() {
            public MessageTypeEnum findValueByNumber(int number) {
              return MessageTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.lwl.netty.message.protobuf.Header.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageTypeEnum[] VALUES = values();

    public static MessageTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageTypeEnum)
  }

  public interface HeaderPOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeaderP)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 msgNum = 1;</code>
     */
    long getMsgNum();

    /**
     * <code>.MessageTypeEnum msgType = 2;</code>
     */
    int getMsgTypeValue();
    /**
     * <code>.MessageTypeEnum msgType = 2;</code>
     */
    org.lwl.netty.message.protobuf.Header.MessageTypeEnum getMsgType();

    /**
     * <code>string msgTime = 3;</code>
     */
    java.lang.String getMsgTime();
    /**
     * <code>string msgTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgTimeBytes();

    /**
     * <code>int32 flag = 4;</code>
     */
    int getFlag();

    /**
     * <code>int32 oneByte = 5;</code>
     */
    int getOneByte();

    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */
    int getAttachmentCount();
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */
    boolean containsAttachment(
        java.lang.String key);
    /**
     * Use {@link #getAttachmentMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAttachment();
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAttachmentMap();
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    java.lang.String getAttachmentOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    java.lang.String getAttachmentOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code HeaderP}
   */
  public  static final class HeaderP extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeaderP)
      HeaderPOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeaderP.newBuilder() to construct.
    private HeaderP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeaderP() {
      msgNum_ = 0L;
      msgType_ = 0;
      msgTime_ = "";
      flag_ = 0;
      oneByte_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeaderP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgNum_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msgTime_ = s;
              break;
            }
            case 32: {

              flag_ = input.readInt32();
              break;
            }
            case 40: {

              oneByte_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                attachment_ = com.google.protobuf.MapField.newMapField(
                    AttachmentDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              attachment__ = input.readMessage(
                  AttachmentDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attachment_.getMutableMap().put(
                  attachment__.getKey(), attachment__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lwl.netty.message.protobuf.Header.internal_static_HeaderP_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetAttachment();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lwl.netty.message.protobuf.Header.internal_static_HeaderP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lwl.netty.message.protobuf.Header.HeaderP.class, org.lwl.netty.message.protobuf.Header.HeaderP.Builder.class);
    }

    private int bitField0_;
    public static final int MSGNUM_FIELD_NUMBER = 1;
    private long msgNum_;
    /**
     * <code>int64 msgNum = 1;</code>
     */
    public long getMsgNum() {
      return msgNum_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <code>.MessageTypeEnum msgType = 2;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.MessageTypeEnum msgType = 2;</code>
     */
    public org.lwl.netty.message.protobuf.Header.MessageTypeEnum getMsgType() {
      @SuppressWarnings("deprecation")
      org.lwl.netty.message.protobuf.Header.MessageTypeEnum result = org.lwl.netty.message.protobuf.Header.MessageTypeEnum.valueOf(msgType_);
      return result == null ? org.lwl.netty.message.protobuf.Header.MessageTypeEnum.UNRECOGNIZED : result;
    }

    public static final int MSGTIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object msgTime_;
    /**
     * <code>string msgTime = 3;</code>
     */
    public java.lang.String getMsgTime() {
      java.lang.Object ref = msgTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgTime_ = s;
        return s;
      }
    }
    /**
     * <code>string msgTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTimeBytes() {
      java.lang.Object ref = msgTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLAG_FIELD_NUMBER = 4;
    private int flag_;
    /**
     * <code>int32 flag = 4;</code>
     */
    public int getFlag() {
      return flag_;
    }

    public static final int ONEBYTE_FIELD_NUMBER = 5;
    private int oneByte_;
    /**
     * <code>int32 oneByte = 5;</code>
     */
    public int getOneByte() {
      return oneByte_;
    }

    public static final int ATTACHMENT_FIELD_NUMBER = 6;
    private static final class AttachmentDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.lwl.netty.message.protobuf.Header.internal_static_HeaderP_AttachmentEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attachment_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttachment() {
      if (attachment_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttachmentDefaultEntryHolder.defaultEntry);
      }
      return attachment_;
    }

    public int getAttachmentCount() {
      return internalGetAttachment().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    public boolean containsAttachment(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttachment().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttachmentMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttachment() {
      return getAttachmentMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAttachmentMap() {
      return internalGetAttachment().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    public java.lang.String getAttachmentOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttachment().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    public java.lang.String getAttachmentOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttachment().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgNum_ != 0L) {
        output.writeInt64(1, msgNum_);
      }
      if (msgType_ != org.lwl.netty.message.protobuf.Header.MessageTypeEnum.UNKNOWN.getNumber()) {
        output.writeEnum(2, msgType_);
      }
      if (!getMsgTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msgTime_);
      }
      if (flag_ != 0) {
        output.writeInt32(4, flag_);
      }
      if (oneByte_ != 0) {
        output.writeInt32(5, oneByte_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttachment(),
          AttachmentDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, msgNum_);
      }
      if (msgType_ != org.lwl.netty.message.protobuf.Header.MessageTypeEnum.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, msgType_);
      }
      if (!getMsgTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msgTime_);
      }
      if (flag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, flag_);
      }
      if (oneByte_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, oneByte_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAttachment().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        attachment__ = AttachmentDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, attachment__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.lwl.netty.message.protobuf.Header.HeaderP)) {
        return super.equals(obj);
      }
      org.lwl.netty.message.protobuf.Header.HeaderP other = (org.lwl.netty.message.protobuf.Header.HeaderP) obj;

      boolean result = true;
      result = result && (getMsgNum()
          == other.getMsgNum());
      result = result && msgType_ == other.msgType_;
      result = result && getMsgTime()
          .equals(other.getMsgTime());
      result = result && (getFlag()
          == other.getFlag());
      result = result && (getOneByte()
          == other.getOneByte());
      result = result && internalGetAttachment().equals(
          other.internalGetAttachment());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGNUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgNum());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + MSGTIME_FIELD_NUMBER;
      hash = (53 * hash) + getMsgTime().hashCode();
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + getFlag();
      hash = (37 * hash) + ONEBYTE_FIELD_NUMBER;
      hash = (53 * hash) + getOneByte();
      if (!internalGetAttachment().getMap().isEmpty()) {
        hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttachment().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.Header.HeaderP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.lwl.netty.message.protobuf.Header.HeaderP prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeaderP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeaderP)
        org.lwl.netty.message.protobuf.Header.HeaderPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.lwl.netty.message.protobuf.Header.internal_static_HeaderP_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.lwl.netty.message.protobuf.Header.internal_static_HeaderP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.lwl.netty.message.protobuf.Header.HeaderP.class, org.lwl.netty.message.protobuf.Header.HeaderP.Builder.class);
      }

      // Construct using org.lwl.netty.message.protobuf.Header.HeaderP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgNum_ = 0L;

        msgType_ = 0;

        msgTime_ = "";

        flag_ = 0;

        oneByte_ = 0;

        internalGetMutableAttachment().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.lwl.netty.message.protobuf.Header.internal_static_HeaderP_descriptor;
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.Header.HeaderP getDefaultInstanceForType() {
        return org.lwl.netty.message.protobuf.Header.HeaderP.getDefaultInstance();
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.Header.HeaderP build() {
        org.lwl.netty.message.protobuf.Header.HeaderP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.Header.HeaderP buildPartial() {
        org.lwl.netty.message.protobuf.Header.HeaderP result = new org.lwl.netty.message.protobuf.Header.HeaderP(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.msgNum_ = msgNum_;
        result.msgType_ = msgType_;
        result.msgTime_ = msgTime_;
        result.flag_ = flag_;
        result.oneByte_ = oneByte_;
        result.attachment_ = internalGetAttachment();
        result.attachment_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.lwl.netty.message.protobuf.Header.HeaderP) {
          return mergeFrom((org.lwl.netty.message.protobuf.Header.HeaderP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.lwl.netty.message.protobuf.Header.HeaderP other) {
        if (other == org.lwl.netty.message.protobuf.Header.HeaderP.getDefaultInstance()) return this;
        if (other.getMsgNum() != 0L) {
          setMsgNum(other.getMsgNum());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (!other.getMsgTime().isEmpty()) {
          msgTime_ = other.msgTime_;
          onChanged();
        }
        if (other.getFlag() != 0) {
          setFlag(other.getFlag());
        }
        if (other.getOneByte() != 0) {
          setOneByte(other.getOneByte());
        }
        internalGetMutableAttachment().mergeFrom(
            other.internalGetAttachment());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.lwl.netty.message.protobuf.Header.HeaderP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.lwl.netty.message.protobuf.Header.HeaderP) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long msgNum_ ;
      /**
       * <code>int64 msgNum = 1;</code>
       */
      public long getMsgNum() {
        return msgNum_;
      }
      /**
       * <code>int64 msgNum = 1;</code>
       */
      public Builder setMsgNum(long value) {
        
        msgNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msgNum = 1;</code>
       */
      public Builder clearMsgNum() {
        
        msgNum_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.MessageTypeEnum msgType = 2;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.MessageTypeEnum msgType = 2;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageTypeEnum msgType = 2;</code>
       */
      public org.lwl.netty.message.protobuf.Header.MessageTypeEnum getMsgType() {
        @SuppressWarnings("deprecation")
        org.lwl.netty.message.protobuf.Header.MessageTypeEnum result = org.lwl.netty.message.protobuf.Header.MessageTypeEnum.valueOf(msgType_);
        return result == null ? org.lwl.netty.message.protobuf.Header.MessageTypeEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageTypeEnum msgType = 2;</code>
       */
      public Builder setMsgType(org.lwl.netty.message.protobuf.Header.MessageTypeEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageTypeEnum msgType = 2;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgTime_ = "";
      /**
       * <code>string msgTime = 3;</code>
       */
      public java.lang.String getMsgTime() {
        java.lang.Object ref = msgTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgTimeBytes() {
        java.lang.Object ref = msgTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgTime = 3;</code>
       */
      public Builder setMsgTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgTime = 3;</code>
       */
      public Builder clearMsgTime() {
        
        msgTime_ = getDefaultInstance().getMsgTime();
        onChanged();
        return this;
      }
      /**
       * <code>string msgTime = 3;</code>
       */
      public Builder setMsgTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgTime_ = value;
        onChanged();
        return this;
      }

      private int flag_ ;
      /**
       * <code>int32 flag = 4;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <code>int32 flag = 4;</code>
       */
      public Builder setFlag(int value) {
        
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 flag = 4;</code>
       */
      public Builder clearFlag() {
        
        flag_ = 0;
        onChanged();
        return this;
      }

      private int oneByte_ ;
      /**
       * <code>int32 oneByte = 5;</code>
       */
      public int getOneByte() {
        return oneByte_;
      }
      /**
       * <code>int32 oneByte = 5;</code>
       */
      public Builder setOneByte(int value) {
        
        oneByte_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 oneByte = 5;</code>
       */
      public Builder clearOneByte() {
        
        oneByte_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> attachment_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAttachment() {
        if (attachment_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        return attachment_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAttachment() {
        onChanged();;
        if (attachment_ == null) {
          attachment_ = com.google.protobuf.MapField.newMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        if (!attachment_.isMutable()) {
          attachment_ = attachment_.copy();
        }
        return attachment_;
      }

      public int getAttachmentCount() {
        return internalGetAttachment().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public boolean containsAttachment(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAttachment().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttachmentMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAttachment() {
        return getAttachmentMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAttachmentMap() {
        return internalGetAttachment().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public java.lang.String getAttachmentOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttachment().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public java.lang.String getAttachmentOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttachment().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAttachment() {
        internalGetMutableAttachment().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public Builder removeAttachment(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttachment().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAttachment() {
        return internalGetMutableAttachment().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */
      public Builder putAttachment(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttachment().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public Builder putAllAttachment(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAttachment().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeaderP)
    }

    // @@protoc_insertion_point(class_scope:HeaderP)
    private static final org.lwl.netty.message.protobuf.Header.HeaderP DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.lwl.netty.message.protobuf.Header.HeaderP();
    }

    public static org.lwl.netty.message.protobuf.Header.HeaderP getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeaderP>
        PARSER = new com.google.protobuf.AbstractParser<HeaderP>() {
      @java.lang.Override
      public HeaderP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeaderP(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeaderP> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeaderP> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.lwl.netty.message.protobuf.Header.HeaderP getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeaderP_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeaderP_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeaderP_AttachmentEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeaderP_AttachmentEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Header.proto\"\315\001\n\007HeaderP\022\016\n\006msgNum\030\001 \001" +
      "(\003\022!\n\007msgType\030\002 \001(\0162\020.MessageTypeEnum\022\017\n" +
      "\007msgTime\030\003 \001(\t\022\014\n\004flag\030\004 \001(\005\022\017\n\007oneByte\030" +
      "\005 \001(\005\022,\n\nattachment\030\006 \003(\0132\030.HeaderP.Atta" +
      "chmentEntry\0321\n\017AttachmentEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*\225\001\n\017MessageTypeEn" +
      "um\022\013\n\007UNKNOWN\020\000\022\r\n\tLOGIN_REQ\020\001\022\016\n\nLOGIN_" +
      "RESP\020\002\022\n\n\006LOGOUT\020\003\022\021\n\rHEARTBEAT_REQ\020\004\022\022\n" +
      "\016HEARTBEAT_RESP\020\005\022\020\n\014PROTOCOL_SUB\020\006\022\021\n\rP" +
      "ROTOCOL_DATA\020\007B(\n\036org.lwl.netty.message." +
      "protobufB\006Headerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeaderP_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeaderP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeaderP_descriptor,
        new java.lang.String[] { "MsgNum", "MsgType", "MsgTime", "Flag", "OneByte", "Attachment", });
    internal_static_HeaderP_AttachmentEntry_descriptor =
      internal_static_HeaderP_descriptor.getNestedTypes().get(0);
    internal_static_HeaderP_AttachmentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeaderP_AttachmentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
