// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolSubBody.proto

package org.lwl.netty.message.protobuf;

public final class ProtocolSubBody {
  private ProtocolSubBody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ProtocolDataType}
   */
  public enum ProtocolDataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT = 0;</code>
     */
    DEFAULT(0),
    /**
     * <code>NEWS = 1;</code>
     */
    NEWS(1),
    /**
     * <code>SPORTS = 2;</code>
     */
    SPORTS(2),
    /**
     * <code>ENTERTAINMENT = 3;</code>
     */
    ENTERTAINMENT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT = 0;</code>
     */
    public static final int DEFAULT_VALUE = 0;
    /**
     * <code>NEWS = 1;</code>
     */
    public static final int NEWS_VALUE = 1;
    /**
     * <code>SPORTS = 2;</code>
     */
    public static final int SPORTS_VALUE = 2;
    /**
     * <code>ENTERTAINMENT = 3;</code>
     */
    public static final int ENTERTAINMENT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtocolDataType valueOf(int value) {
      return forNumber(value);
    }

    public static ProtocolDataType forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT;
        case 1: return NEWS;
        case 2: return SPORTS;
        case 3: return ENTERTAINMENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolDataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtocolDataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolDataType>() {
            public ProtocolDataType findValueByNumber(int number) {
              return ProtocolDataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.lwl.netty.message.protobuf.ProtocolSubBody.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtocolDataType[] VALUES = values();

    public static ProtocolDataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtocolDataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtocolDataType)
  }

  public interface ProtocolSubBodyPOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtocolSubBodyP)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    java.util.List<org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType> getDataTypeListList();
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    int getDataTypeListCount();
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType getDataTypeList(int index);
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    java.util.List<java.lang.Integer>
    getDataTypeListValueList();
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    int getDataTypeListValue(int index);
  }
  /**
   * Protobuf type {@code ProtocolSubBodyP}
   */
  public  static final class ProtocolSubBodyP extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtocolSubBodyP)
      ProtocolSubBodyPOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtocolSubBodyP.newBuilder() to construct.
    private ProtocolSubBodyP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolSubBodyP() {
      dataTypeList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtocolSubBodyP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dataTypeList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              dataTypeList_.add(rawValue);
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  dataTypeList_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000001;
                }
                dataTypeList_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dataTypeList_ = java.util.Collections.unmodifiableList(dataTypeList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lwl.netty.message.protobuf.ProtocolSubBody.internal_static_ProtocolSubBodyP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lwl.netty.message.protobuf.ProtocolSubBody.internal_static_ProtocolSubBodyP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP.class, org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP.Builder.class);
    }

    public static final int DATATYPELIST_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> dataTypeList_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType> dataTypeList_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType>() {
              public org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType result = org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType.valueOf(from);
                return result == null ? org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    public java.util.List<org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType> getDataTypeListList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType>(dataTypeList_, dataTypeList_converter_);
    }
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    public int getDataTypeListCount() {
      return dataTypeList_.size();
    }
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    public org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType getDataTypeList(int index) {
      return dataTypeList_converter_.convert(dataTypeList_.get(index));
    }
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    public java.util.List<java.lang.Integer>
    getDataTypeListValueList() {
      return dataTypeList_;
    }
    /**
     * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
     */
    public int getDataTypeListValue(int index) {
      return dataTypeList_.get(index);
    }
    private int dataTypeListMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getDataTypeListList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(dataTypeListMemoizedSerializedSize);
      }
      for (int i = 0; i < dataTypeList_.size(); i++) {
        output.writeEnumNoTag(dataTypeList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < dataTypeList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(dataTypeList_.get(i));
        }
        size += dataSize;
        if (!getDataTypeListList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }dataTypeListMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP)) {
        return super.equals(obj);
      }
      org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP other = (org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP) obj;

      boolean result = true;
      result = result && dataTypeList_.equals(other.dataTypeList_);
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataTypeListCount() > 0) {
        hash = (37 * hash) + DATATYPELIST_FIELD_NUMBER;
        hash = (53 * hash) + dataTypeList_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtocolSubBodyP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtocolSubBodyP)
        org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.lwl.netty.message.protobuf.ProtocolSubBody.internal_static_ProtocolSubBodyP_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.lwl.netty.message.protobuf.ProtocolSubBody.internal_static_ProtocolSubBodyP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP.class, org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP.Builder.class);
      }

      // Construct using org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataTypeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.lwl.netty.message.protobuf.ProtocolSubBody.internal_static_ProtocolSubBodyP_descriptor;
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP getDefaultInstanceForType() {
        return org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP.getDefaultInstance();
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP build() {
        org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP buildPartial() {
        org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP result = new org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          dataTypeList_ = java.util.Collections.unmodifiableList(dataTypeList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dataTypeList_ = dataTypeList_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP) {
          return mergeFrom((org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP other) {
        if (other == org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP.getDefaultInstance()) return this;
        if (!other.dataTypeList_.isEmpty()) {
          if (dataTypeList_.isEmpty()) {
            dataTypeList_ = other.dataTypeList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataTypeListIsMutable();
            dataTypeList_.addAll(other.dataTypeList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> dataTypeList_ =
        java.util.Collections.emptyList();
      private void ensureDataTypeListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dataTypeList_ = new java.util.ArrayList<java.lang.Integer>(dataTypeList_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public java.util.List<org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType> getDataTypeListList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType>(dataTypeList_, dataTypeList_converter_);
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public int getDataTypeListCount() {
        return dataTypeList_.size();
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType getDataTypeList(int index) {
        return dataTypeList_converter_.convert(dataTypeList_.get(index));
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public Builder setDataTypeList(
          int index, org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataTypeListIsMutable();
        dataTypeList_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public Builder addDataTypeList(org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataTypeListIsMutable();
        dataTypeList_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public Builder addAllDataTypeList(
          java.lang.Iterable<? extends org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType> values) {
        ensureDataTypeListIsMutable();
        for (org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolDataType value : values) {
          dataTypeList_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public Builder clearDataTypeList() {
        dataTypeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public java.util.List<java.lang.Integer>
      getDataTypeListValueList() {
        return java.util.Collections.unmodifiableList(dataTypeList_);
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public int getDataTypeListValue(int index) {
        return dataTypeList_.get(index);
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public Builder setDataTypeListValue(
          int index, int value) {
        ensureDataTypeListIsMutable();
        dataTypeList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public Builder addDataTypeListValue(int value) {
        ensureDataTypeListIsMutable();
        dataTypeList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .ProtocolDataType dataTypeList = 1;</code>
       */
      public Builder addAllDataTypeListValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureDataTypeListIsMutable();
        for (int value : values) {
          dataTypeList_.add(value);
        }
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtocolSubBodyP)
    }

    // @@protoc_insertion_point(class_scope:ProtocolSubBodyP)
    private static final org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP();
    }

    public static org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtocolSubBodyP>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolSubBodyP>() {
      @java.lang.Override
      public ProtocolSubBodyP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtocolSubBodyP(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtocolSubBodyP> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolSubBodyP> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.lwl.netty.message.protobuf.ProtocolSubBody.ProtocolSubBodyP getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolSubBodyP_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtocolSubBodyP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ProtocolSubBody.proto\";\n\020ProtocolSubBo" +
      "dyP\022\'\n\014dataTypeList\030\001 \003(\0162\021.ProtocolData" +
      "Type*H\n\020ProtocolDataType\022\013\n\007DEFAULT\020\000\022\010\n" +
      "\004NEWS\020\001\022\n\n\006SPORTS\020\002\022\021\n\rENTERTAINMENT\020\003B1" +
      "\n\036org.lwl.netty.message.protobufB\017Protoc" +
      "olSubBodyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtocolSubBodyP_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtocolSubBodyP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtocolSubBodyP_descriptor,
        new java.lang.String[] { "DataTypeList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
