// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolDataBody.proto

package org.lwl.netty.message.protobuf;

public final class ProtocolDataBody {
  private ProtocolDataBody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolDataBodyPOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtocolDataBodyP)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint64 pkgSum = 1;</code>
     */
    long getPkgSum();

    /**
     * <code>sint64 pkgSequenceNum = 2;</code>
     */
    long getPkgSequenceNum();

    /**
     * <code>int32 contentLen = 3;</code>
     */
    int getContentLen();

    /**
     * <code>bytes content = 4;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code ProtocolDataBodyP}
   */
  public  static final class ProtocolDataBodyP extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtocolDataBodyP)
      ProtocolDataBodyPOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtocolDataBodyP.newBuilder() to construct.
    private ProtocolDataBodyP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolDataBodyP() {
      pkgSum_ = 0L;
      pkgSequenceNum_ = 0L;
      contentLen_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtocolDataBodyP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pkgSum_ = input.readSInt64();
              break;
            }
            case 16: {

              pkgSequenceNum_ = input.readSInt64();
              break;
            }
            case 24: {

              contentLen_ = input.readInt32();
              break;
            }
            case 34: {

              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lwl.netty.message.protobuf.ProtocolDataBody.internal_static_ProtocolDataBodyP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lwl.netty.message.protobuf.ProtocolDataBody.internal_static_ProtocolDataBodyP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP.class, org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP.Builder.class);
    }

    public static final int PKGSUM_FIELD_NUMBER = 1;
    private long pkgSum_;
    /**
     * <code>sint64 pkgSum = 1;</code>
     */
    public long getPkgSum() {
      return pkgSum_;
    }

    public static final int PKGSEQUENCENUM_FIELD_NUMBER = 2;
    private long pkgSequenceNum_;
    /**
     * <code>sint64 pkgSequenceNum = 2;</code>
     */
    public long getPkgSequenceNum() {
      return pkgSequenceNum_;
    }

    public static final int CONTENTLEN_FIELD_NUMBER = 3;
    private int contentLen_;
    /**
     * <code>int32 contentLen = 3;</code>
     */
    public int getContentLen() {
      return contentLen_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 4;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pkgSum_ != 0L) {
        output.writeSInt64(1, pkgSum_);
      }
      if (pkgSequenceNum_ != 0L) {
        output.writeSInt64(2, pkgSequenceNum_);
      }
      if (contentLen_ != 0) {
        output.writeInt32(3, contentLen_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pkgSum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, pkgSum_);
      }
      if (pkgSequenceNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, pkgSequenceNum_);
      }
      if (contentLen_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, contentLen_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP)) {
        return super.equals(obj);
      }
      org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP other = (org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP) obj;

      boolean result = true;
      result = result && (getPkgSum()
          == other.getPkgSum());
      result = result && (getPkgSequenceNum()
          == other.getPkgSequenceNum());
      result = result && (getContentLen()
          == other.getContentLen());
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PKGSUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPkgSum());
      hash = (37 * hash) + PKGSEQUENCENUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPkgSequenceNum());
      hash = (37 * hash) + CONTENTLEN_FIELD_NUMBER;
      hash = (53 * hash) + getContentLen();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtocolDataBodyP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtocolDataBodyP)
        org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.lwl.netty.message.protobuf.ProtocolDataBody.internal_static_ProtocolDataBodyP_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.lwl.netty.message.protobuf.ProtocolDataBody.internal_static_ProtocolDataBodyP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP.class, org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP.Builder.class);
      }

      // Construct using org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pkgSum_ = 0L;

        pkgSequenceNum_ = 0L;

        contentLen_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.lwl.netty.message.protobuf.ProtocolDataBody.internal_static_ProtocolDataBodyP_descriptor;
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP getDefaultInstanceForType() {
        return org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP.getDefaultInstance();
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP build() {
        org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP buildPartial() {
        org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP result = new org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP(this);
        result.pkgSum_ = pkgSum_;
        result.pkgSequenceNum_ = pkgSequenceNum_;
        result.contentLen_ = contentLen_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP) {
          return mergeFrom((org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP other) {
        if (other == org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP.getDefaultInstance()) return this;
        if (other.getPkgSum() != 0L) {
          setPkgSum(other.getPkgSum());
        }
        if (other.getPkgSequenceNum() != 0L) {
          setPkgSequenceNum(other.getPkgSequenceNum());
        }
        if (other.getContentLen() != 0) {
          setContentLen(other.getContentLen());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long pkgSum_ ;
      /**
       * <code>sint64 pkgSum = 1;</code>
       */
      public long getPkgSum() {
        return pkgSum_;
      }
      /**
       * <code>sint64 pkgSum = 1;</code>
       */
      public Builder setPkgSum(long value) {
        
        pkgSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 pkgSum = 1;</code>
       */
      public Builder clearPkgSum() {
        
        pkgSum_ = 0L;
        onChanged();
        return this;
      }

      private long pkgSequenceNum_ ;
      /**
       * <code>sint64 pkgSequenceNum = 2;</code>
       */
      public long getPkgSequenceNum() {
        return pkgSequenceNum_;
      }
      /**
       * <code>sint64 pkgSequenceNum = 2;</code>
       */
      public Builder setPkgSequenceNum(long value) {
        
        pkgSequenceNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 pkgSequenceNum = 2;</code>
       */
      public Builder clearPkgSequenceNum() {
        
        pkgSequenceNum_ = 0L;
        onChanged();
        return this;
      }

      private int contentLen_ ;
      /**
       * <code>int32 contentLen = 3;</code>
       */
      public int getContentLen() {
        return contentLen_;
      }
      /**
       * <code>int32 contentLen = 3;</code>
       */
      public Builder setContentLen(int value) {
        
        contentLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contentLen = 3;</code>
       */
      public Builder clearContentLen() {
        
        contentLen_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 4;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtocolDataBodyP)
    }

    // @@protoc_insertion_point(class_scope:ProtocolDataBodyP)
    private static final org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP();
    }

    public static org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtocolDataBodyP>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolDataBodyP>() {
      @java.lang.Override
      public ProtocolDataBodyP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtocolDataBodyP(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtocolDataBodyP> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolDataBodyP> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.lwl.netty.message.protobuf.ProtocolDataBody.ProtocolDataBodyP getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolDataBodyP_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtocolDataBodyP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ProtocolDataBody.proto\"`\n\021ProtocolData" +
      "BodyP\022\016\n\006pkgSum\030\001 \001(\022\022\026\n\016pkgSequenceNum\030" +
      "\002 \001(\022\022\022\n\ncontentLen\030\003 \001(\005\022\017\n\007content\030\004 \001" +
      "(\014B2\n\036org.lwl.netty.message.protobufB\020Pr" +
      "otocolDataBodyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtocolDataBodyP_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtocolDataBodyP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtocolDataBodyP_descriptor,
        new java.lang.String[] { "PkgSum", "PkgSequenceNum", "ContentLen", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
