// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tail.proto

package org.lwl.netty.message.protobuf;

public final class Tail {
  private Tail() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TailPOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TailP)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 checkSum = 1;</code>
     */
    int getCheckSum();
  }
  /**
   * Protobuf type {@code TailP}
   */
  public  static final class TailP extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TailP)
      TailPOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TailP.newBuilder() to construct.
    private TailP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TailP() {
      checkSum_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TailP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              checkSum_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lwl.netty.message.protobuf.Tail.internal_static_TailP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lwl.netty.message.protobuf.Tail.internal_static_TailP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lwl.netty.message.protobuf.Tail.TailP.class, org.lwl.netty.message.protobuf.Tail.TailP.Builder.class);
    }

    public static final int CHECKSUM_FIELD_NUMBER = 1;
    private int checkSum_;
    /**
     * <code>int32 checkSum = 1;</code>
     */
    public int getCheckSum() {
      return checkSum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (checkSum_ != 0) {
        output.writeInt32(1, checkSum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (checkSum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, checkSum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.lwl.netty.message.protobuf.Tail.TailP)) {
        return super.equals(obj);
      }
      org.lwl.netty.message.protobuf.Tail.TailP other = (org.lwl.netty.message.protobuf.Tail.TailP) obj;

      boolean result = true;
      result = result && (getCheckSum()
          == other.getCheckSum());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getCheckSum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.lwl.netty.message.protobuf.Tail.TailP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.lwl.netty.message.protobuf.Tail.TailP prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TailP}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TailP)
        org.lwl.netty.message.protobuf.Tail.TailPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.lwl.netty.message.protobuf.Tail.internal_static_TailP_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.lwl.netty.message.protobuf.Tail.internal_static_TailP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.lwl.netty.message.protobuf.Tail.TailP.class, org.lwl.netty.message.protobuf.Tail.TailP.Builder.class);
      }

      // Construct using org.lwl.netty.message.protobuf.Tail.TailP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        checkSum_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.lwl.netty.message.protobuf.Tail.internal_static_TailP_descriptor;
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.Tail.TailP getDefaultInstanceForType() {
        return org.lwl.netty.message.protobuf.Tail.TailP.getDefaultInstance();
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.Tail.TailP build() {
        org.lwl.netty.message.protobuf.Tail.TailP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.lwl.netty.message.protobuf.Tail.TailP buildPartial() {
        org.lwl.netty.message.protobuf.Tail.TailP result = new org.lwl.netty.message.protobuf.Tail.TailP(this);
        result.checkSum_ = checkSum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.lwl.netty.message.protobuf.Tail.TailP) {
          return mergeFrom((org.lwl.netty.message.protobuf.Tail.TailP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.lwl.netty.message.protobuf.Tail.TailP other) {
        if (other == org.lwl.netty.message.protobuf.Tail.TailP.getDefaultInstance()) return this;
        if (other.getCheckSum() != 0) {
          setCheckSum(other.getCheckSum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.lwl.netty.message.protobuf.Tail.TailP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.lwl.netty.message.protobuf.Tail.TailP) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int checkSum_ ;
      /**
       * <code>int32 checkSum = 1;</code>
       */
      public int getCheckSum() {
        return checkSum_;
      }
      /**
       * <code>int32 checkSum = 1;</code>
       */
      public Builder setCheckSum(int value) {
        
        checkSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 checkSum = 1;</code>
       */
      public Builder clearCheckSum() {
        
        checkSum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TailP)
    }

    // @@protoc_insertion_point(class_scope:TailP)
    private static final org.lwl.netty.message.protobuf.Tail.TailP DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.lwl.netty.message.protobuf.Tail.TailP();
    }

    public static org.lwl.netty.message.protobuf.Tail.TailP getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TailP>
        PARSER = new com.google.protobuf.AbstractParser<TailP>() {
      @java.lang.Override
      public TailP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TailP(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TailP> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TailP> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.lwl.netty.message.protobuf.Tail.TailP getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TailP_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TailP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTail.proto\"\031\n\005TailP\022\020\n\010checkSum\030\001 \001(\005B" +
      "&\n\036org.lwl.netty.message.protobufB\004Tailb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TailP_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TailP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TailP_descriptor,
        new java.lang.String[] { "CheckSum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
